// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcpWCPZrH1I9sj5VRb3MFpgWNVP9z5qY',
    appId: '1:1092429069299:web:65bf89dc50523bb9eeb086',
    messagingSenderId: '1092429069299',
    projectId: 'free-mind-d8631',
    authDomain: 'free-mind-d8631.firebaseapp.com',
    storageBucket: 'free-mind-d8631.firebasestorage.app',
    measurementId: 'G-HZXCMLHF4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLzxbpFGWw1UITU_f9PZF_O4EQCFJ9t4',
    appId: '1:1092429069299:android:25332d9233958bffeeb086',
    messagingSenderId: '1092429069299',
    projectId: 'free-mind-d8631',
    storageBucket: 'free-mind-d8631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8tqH_a0OJHOjCmkjYNKQu_GGfM5Qgk0',
    appId: '1:1092429069299:ios:f9476111ebc6bbd3eeb086',
    messagingSenderId: '1092429069299',
    projectId: 'free-mind-d8631',
    storageBucket: 'free-mind-d8631.firebasestorage.app',
    iosBundleId: 'com.example.freeMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH8tqH_a0OJHOjCmkjYNKQu_GGfM5Qgk0',
    appId: '1:1092429069299:ios:f9476111ebc6bbd3eeb086',
    messagingSenderId: '1092429069299',
    projectId: 'free-mind-d8631',
    storageBucket: 'free-mind-d8631.firebasestorage.app',
    iosBundleId: 'com.example.freeMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdcpWCPZrH1I9sj5VRb3MFpgWNVP9z5qY',
    appId: '1:1092429069299:web:014cfbd1c25e000deeb086',
    messagingSenderId: '1092429069299',
    projectId: 'free-mind-d8631',
    authDomain: 'free-mind-d8631.firebaseapp.com',
    storageBucket: 'free-mind-d8631.firebasestorage.app',
    measurementId: 'G-Y3ED9ZQLCM',
  );
}
