// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB89doyWJwqaCkpeYAKbS_bMjijgEP-3k',
    appId: '1:208217148439:web:bb4a21556f441244f02052',
    messagingSenderId: '208217148439',
    projectId: 'relaxmind-4885d',
    authDomain: 'relaxmind-4885d.firebaseapp.com',
    storageBucket: 'relaxmind-4885d.firebasestorage.app',
    measurementId: 'G-C7TTRVFP90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1_NkXZKYvBQZTpeDINww9wV-Df6zZGo',
    appId: '1:208217148439:android:f964731590140802f02052',
    messagingSenderId: '208217148439',
    projectId: 'relaxmind-4885d',
    storageBucket: 'relaxmind-4885d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARm1IvFeHgg8A7rcnrJhlqKiahm5yryuw',
    appId: '1:208217148439:ios:586204212aed1c98f02052',
    messagingSenderId: '208217148439',
    projectId: 'relaxmind-4885d',
    storageBucket: 'relaxmind-4885d.firebasestorage.app',
    androidClientId: '208217148439-6eotg8s4lfp8h5oc47l3cfbt795o0fbl.apps.googleusercontent.com',
    iosClientId: '208217148439-u0ghbnf80iinuvasfg4g5dpiauqlls67.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARm1IvFeHgg8A7rcnrJhlqKiahm5yryuw',
    appId: '1:208217148439:ios:586204212aed1c98f02052',
    messagingSenderId: '208217148439',
    projectId: 'relaxmind-4885d',
    storageBucket: 'relaxmind-4885d.firebasestorage.app',
    androidClientId: '208217148439-6eotg8s4lfp8h5oc47l3cfbt795o0fbl.apps.googleusercontent.com',
    iosClientId: '208217148439-u0ghbnf80iinuvasfg4g5dpiauqlls67.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB89doyWJwqaCkpeYAKbS_bMjijgEP-3k',
    appId: '1:208217148439:web:9b3f4acd2ac5d402f02052',
    messagingSenderId: '208217148439',
    projectId: 'relaxmind-4885d',
    authDomain: 'relaxmind-4885d.firebaseapp.com',
    storageBucket: 'relaxmind-4885d.firebasestorage.app',
    measurementId: 'G-837KW1YFJG',
  );
}
